#!/usr/bin/env python3
"""
Create a test PDF with text for OCR testing.
"""

from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import Table, TableStyle
import os

def create_test_pdf():
    """Create a test PDF with text and tables for OCR testing."""
    filename = "test_document.pdf"
    c = canvas.Canvas(filename, pagesize=letter)
    width, height = letter
    
    # Title
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, height - 50, "Test Document for OCR")
    
    # Regular text
    c.setFont("Helvetica", 12)
    y_position = height - 100
    
    text_lines = [
        "This is a test document created for OCR functionality testing.",
        "It contains various types of content including:",
        "• Regular text paragraphs",
        "• Numbered lists",
        "• Tables with data",
        "• Different font sizes and styles",
        "",
        "Sample Invoice Data:",
        "Invoice Number: INV-2024-001",
        "Date: August 27, 2024",
        "Amount: $1,234.56",
        "Tax: $123.46",
        "Total: $1,358.02"
    ]
    
    for line in text_lines:
        c.drawString(50, y_position, line)
        y_position -= 20
    
    # Create a simple table
    y_position -= 40
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y_position, "Sample Table:")
    
    y_position -= 30
    c.setFont("Helvetica", 10)
    
    # Table headers
    headers = ["Product", "Quantity", "Price", "Total"]
    col_widths = [150, 80, 80, 80]
    x_positions = [50, 200, 280, 360]
    
    # Draw table headers
    for i, header in enumerate(headers):
        c.setFont("Helvetica-Bold", 10)
        c.drawString(x_positions[i], y_position, header)
    
    y_position -= 20
    
    # Table data
    table_data = [
        ["Widget A", "10", "$25.00", "$250.00"],
        ["Widget B", "5", "$45.00", "$225.00"],
        ["Widget C", "3", "$75.00", "$225.00"],
        ["Subtotal", "", "", "$700.00"],
        ["Tax (10%)", "", "", "$70.00"],
        ["Total", "", "", "$770.00"]
    ]
    
    for row in table_data:
        c.setFont("Helvetica", 10)
        for i, cell in enumerate(row):
            if i == 0 and row[0] in ["Subtotal", "Tax (10%)", "Total"]:
                c.setFont("Helvetica-Bold", 10)
            c.drawString(x_positions[i], y_position, cell)
        y_position -= 15
    
    # Add some formatted numbers for testing
    y_position -= 30
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y_position, "Number Formats:")
    
    y_position -= 25
    c.setFont("Helvetica", 10)
    number_examples = [
        "Currency: $1,234.56, €987.65, £543.21",
        "Percentages: 15.5%, 100%, 0.25%",
        "Dates: 2024-08-27, 08/27/2024, August 27, 2024",
        "Phone: (555) 123-4567, +1-555-987-6543",
        "Decimals: 3.14159, 2.71828, 1.41421"
    ]
    
    for example in number_examples:
        c.drawString(50, y_position, example)
        y_position -= 15
    
    # Footer
    c.setFont("Helvetica", 8)
    c.drawString(50, 50, "Generated by PDFX-Bench OCR Test Suite")
    
    c.save()
    print(f"Created test PDF: {filename}")
    return filename

if __name__ == "__main__":
    try:
        import reportlab
        pdf_file = create_test_pdf()
        print(f"Test PDF created successfully: {pdf_file}")
    except ImportError:
        print("reportlab not installed. Installing...")
        import subprocess
        subprocess.run(["pip", "install", "reportlab"])
        pdf_file = create_test_pdf()
        print(f"Test PDF created successfully: {pdf_file}")
